### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by thedrow** [gburd/libumem#10]
Just checking for maintenance status because last commit was in 2012 and last release was in 2010.
Is this still being used by someone?

**Comment by gburd** [comment]
I have no idea if it's used outside of Solaris/OpenSolaris/Illumos/SmartOS universe (where it is the default malloc implementation).  This code is just the port of that into the Linux world, I doubt it is heavily used as such.  That's not to say it's not useful, functional, and perhaps even as good or better than the alternatives, it's just less well known and not top of my priority list for maintenance.
